# Copyright 2026 Google LLC

import datetime
from typing import Any

from app.database import (
    get_all_stores_telemetry,
    get_purchase_orders,
    insert_purchase_order,
)

SUPPLIER_CATALOG = {
    "cymbal-roasters": {
        "supplier_name": "Cymbal Artisan Roasters Direct",
        "lead_time_hours_expedited": 2,
        "price_per_kg": 18.50,
    },
}


def analyze_consumption_patterns(
    store_id: str = "downtown-flagship",
    item_key: str = "dark-roast-beans",
    forecast_hours: int = 48,
) -> dict[str, Any]:
    all_stores = get_all_stores_telemetry()
    store = all_stores.get(store_id)
    if not store or item_key not in store["bins"]:
        return {"error": f"Item '{item_key}' not found at store '{store_id}'."}

    bin_data = store["bins"][item_key]
    return {
        "store_id": store_id,
        "item_name": bin_data["item_name"],
        "current_stock_kg": bin_data["current_weight_kg"],
        "hourly_consumption_rate_kg": bin_data["hourly_consumption_kg"],
        "estimated_hours_until_stockout": 2.0,
        "recommendation": {
            "action": "EXPEDITED_REORDER_REQUIRED",
            "recommended_quantity_kg": 40.0,
        },
    }


def create_purchase_order(
    store_id: str = "downtown-flagship",
    item_key: str = "dark-roast-beans",
    quantity_kg: float = 40.0,
    urgency: str = "EXPEDITED",
) -> dict[str, Any]:
    """Create and persist a Purchase Order into the SQLite database."""
    all_stores = get_all_stores_telemetry()
    store = all_stores.get(store_id)
    item_name = store["bins"][item_key]["item_name"] if (store and item_key in store["bins"]) else "Dark Roast"
    supplier = SUPPLIER_CATALOG["cymbal-roasters"]
    total_cost = round(quantity_kg * float(supplier["price_per_kg"]), 2)

    po_data = {
        "store_id": store_id,
        "supplier": supplier["supplier_name"],
        "item_name": item_name,
        "quantity_kg": quantity_kg,
        "urgency": urgency,
        "status": "ROUTED_TO_FULFILLMENT",
        "eta_delivery": (datetime.datetime.now() + datetime.timedelta(hours=2)).strftime("%Y-%m-%d %H:%M:%S"),
        "notes": f"Total Cost: ${total_cost} USD. Auto-generated by Cymbal Procurement Agent.",
    }

    inserted_po = insert_purchase_order(po_data)
    inserted_po["total_cost_usd"] = total_cost
    inserted_po["supplier_name"] = supplier["supplier_name"]
    inserted_po["delivery_eta"] = inserted_po["eta_delivery"]

    return {
        "success": True,
        "purchase_order": inserted_po,
        "total_active_orders": len(get_purchase_orders()),
    }
